#! /bin/bash
cd /tensorbuilder
PYTHONPATH= pdoc --html-dir=docs --html tensorbuilder --only-pypath --overwrite
python -c "from tensorbuilder import tb; import os; open('README.md', 'w').write(tb.__doc__); open('guide/README.md', 'w').write(tb.__doc__)"
