#! /bin/bash
cd /tensorbuilder
#PYTHONPATH= pdoc --html-dir=docs --html tensorbuilder --only-pypath --overwrite
python -c "import tensorbuilder as tb; import os; open('README.md', 'w').write(tb.__doc__)"
